### ISSUE TITLE
Error connection - ECONNREFUSED 127.0.0.1:42047

### ISSUE THREAD

**Issue by srikanthkolli** [artlimes/meteor-chrome-headless-spiderable#5]
I'm getting below error when using this package with reaction commerce cache plugin. When i change the chrome setting to include `--no-sandbox` it works without any issue.

```
UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:42047
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
(node:682) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

```

**Comment by prosf** [comment]
@srikanthkolli
It seems that currently there is no need for this flag(At least for the latest Chrome versions). If this bug can't be replicated anymore we can
close this issue for now.
